#!/bin/sh  /etc/rc.common
. /lib/functions.sh

log() {
	logger -t "20-mount" "$@"
}

if [ ! -f /tmp/bootend.file ]; then
	sleep 10
	while [ ! -f /tmp/bootend.file ]; do
		sleep 1
	done
	log "Delay Block Mount for boot up"
fi

blkdev=`dirname $DEVPATH` 
if [ `basename $blkdev` != "block" ]; then 
	device=`basename $DEVPATH` 
	if echo $device | grep -q "mtdblock"; then
		exit 0
	fi

	case "$ACTION" in 
		add) 
			mkdir -p /mnt/$device 
			# vfat & ntfs-3g check 
			if [ `which fdisk` ]; then 
				isntfs=`fdisk -l | grep $device | grep NTFS` 
				isvfat=`fdisk -l | grep $device | grep FAT` 
				isfuse=`lsmod | grep fuse` 
				isntfs3g=`which ntfs-3g` 
			else 
				isntfs="" 
				isvfat="" 
			fi 
			# mount with ntfs-3g if possible, else with default mount 
			if [ "$isntfs" -a "$isfuse" -a "$isntfs3g" ]; then 
				ntfs-3g -o nls=utf8 /dev/$device /mnt/$device 
				log "Mount /mnt/$device as NTFS"
			elif [ "$isvfat" ]; then 
				mount -o codepage=437,iocharset=iso8859-1 /dev/$device /mnt/$device 
				log "Mount /mnt/$device as FAT"
			else 
				mount /dev/$device /mnt/$device 
				log "Mount /mnt/$device as other"
			fi 
		;; 
	esac 
fi